package com.zsc.map;



/**
 * Inforname generated by MyEclipse - Hibernate Tools
 */

public class Inforname{


    // Fields    

     private Integer id;
     private String inforname;
     private Integer weizhi;
     private String beizhu;
     private String path;
     private Integer style;

    // Constructors

    /** default constructor */
    public Inforname() {
    }

    
   

   
    // Property accessors

    public String getPath() {
		return path;
	}





	public void setPath(String path) {
		this.path = path;
	}





	public Inforname(Integer id, String inforname, Integer weizhi, String beizhu, String path, Integer style) {
		super();
		this.id = id;
		this.inforname = inforname;
		this.weizhi = weizhi;
		this.beizhu = beizhu;
		this.path = path;
		this.style = style;
	}





	public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getInforname() {
        return this.inforname;
    }
    
    public void setInforname(String inforname) {
        this.inforname = inforname;
    }

    public Integer getWeizhi() {
        return this.weizhi;
    }
    
    public void setWeizhi(Integer weizhi) {
        this.weizhi = weizhi;
    }

    public String getBeizhu() {
        return this.beizhu;
    }
    
    public void setBeizhu(String beizhu) {
        this.beizhu = beizhu;
    }


	public Integer getStyle() {
		return style;
	}


	public void setStyle(Integer style) {
		this.style = style;
	}
   








}