package com.zsc.map;

import java.sql.Date;


/**
 * Infor generated by MyEclipse - Hibernate Tools
 */

public class Infor  {


    // Fields    

     private Integer id;
     private String inforname;
     private String biaoti;
 	@com.zsc.util.Type(value ="CLOB")     
     private String gaiyao;
  
     private Integer liulangcishu;
     private String wenjian;
     private String tupian;
     private String wenbieming;
     private String tubiming;
     private Date times;


    // Constructors

    /** default constructor */
    public Infor() {
    }

	/** minimal constructor */
    public Infor(Integer id, String inforname, String biaoti, String gaiyao, Integer liulangcishu, Date times) {
        this.id = id;
        this.inforname = inforname;
        this.biaoti = biaoti;
        this.gaiyao = gaiyao;
    
        this.liulangcishu = liulangcishu;
        this.times = times;
    }
    
    /** full constructor */
    public Infor(Integer id, String inforname, String biaoti, String gaiyao, Integer liulangcishu, String wenjian, String tupian, String wenbieming, String tubiming, Date times) {
        this.id = id;
        this.inforname = inforname;
        this.biaoti = biaoti;
        this.gaiyao = gaiyao;
      
        this.liulangcishu = liulangcishu;
        this.wenjian = wenjian;
        this.tupian = tupian;
        this.wenbieming = wenbieming;
        this.tubiming = tubiming;
        this.times = times;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getInforname() {
        return this.inforname;
    }
    
    public void setInforname(String inforname) {
        this.inforname = inforname;
    }

    public String getBiaoti() {
        return this.biaoti;
    }
    
    public void setBiaoti(String biaoti) {
        this.biaoti = biaoti;
    }

    public String getGaiyao() {
        return this.gaiyao;
    }
    
    public void setGaiyao(String gaiyao) {
        this.gaiyao = gaiyao;
    }

 

    public Integer getLiulangcishu() {
        return this.liulangcishu;
    }
    
    public void setLiulangcishu(Integer liulangcishu) {
        this.liulangcishu = liulangcishu;
    }

    public String getWenjian() {
        return this.wenjian;
    }
    
    public void setWenjian(String wenjian) {
        this.wenjian = wenjian;
    }

    public String getTupian() {
        return this.tupian;
    }
    
    public void setTupian(String tupian) {
        this.tupian = tupian;
    }

    public String getWenbieming() {
        return this.wenbieming;
    }
    
    public void setWenbieming(String wenbieming) {
        this.wenbieming = wenbieming;
    }

    public String getTubiming() {
        return this.tubiming;
    }
    
    public void setTubiming(String tubiming) {
        this.tubiming = tubiming;
    }

    public Date getTimes() {
        return this.times;
    }
    
    public void setTimes(Date times) {
        this.times = times;
    }
   








}